### ISSUE TITLE
Add the Reader Revenue Control Panel to tools.gutools.co.uk

### ISSUE THREAD

**Issue by rtyley** [guardian/support-admin-console#440]
If you've not seen it before, https://tools.gutools.co.uk/ is a great tool for discovering tools created & maintained by P&E:

![image](https://user-images.githubusercontent.com/52038/230342607-4276ac85-40be-4479-80c1-062326b48fe7.png)

It can help with discovering CODE environments, the relevant GitHub repo, logs & metrics, etc associated with the tool. Could you add the Reader Revenue Control Panel (https://support.gutools.co.uk/)?

The config can be added here: https://github.com/guardian/tools-index/tree/7656c011f/client/src/config - see https://github.com/guardian/tools-index/pull/150 as an example PR.

**Comment by sookburt** [comment]
It looks like this was done at some point without this being updated.
